cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED SNAPTRAY_BUILD_DIR OR NOT DEFINED SNAPTRAY_BUILD_TYPE OR "$ENV{QT_PATH}" STREQUAL "")
    message(FATAL_ERROR "Build directory, build type and QT_PATH are required")
endif()
get_filename_component(build_dir "${SNAPTRAY_BUILD_DIR}" ABSOLUTE)
get_filename_component(qt_prefix "$ENV{QT_PATH}" REALPATH)
set(suffix "")
set(app_name SnapTray)
if(SNAPTRAY_BUILD_TYPE STREQUAL "Debug")
    set(app_name SnapTray-Debug)
    if(EXISTS "${qt_prefix}/bin/Qt6Cored.dll")
        set(suffix d)
    endif()
endif()
set(executable "${build_dir}/bin/${app_name}.exe")
if(NOT EXISTS "${executable}")
    message(FATAL_ERROR "Built application not found: ${executable}")
endif()

set(pending "${build_dir}/.qt-deploy-pending")
set(needs_deploy FALSE)
if(EXISTS "${pending}")
    set(needs_deploy TRUE)
endif()
foreach(module Core Gui Widgets Qml Quick QuickWidgets)
    if(NOT EXISTS "${build_dir}/bin/Qt6${module}${suffix}.dll")
        set(needs_deploy TRUE)
    endif()
endforeach()
foreach(required "platforms/qwindows${suffix}.dll" "qml/QtQuick/Layouts" "qml/QtQuick/Controls/Basic")
    if(NOT EXISTS "${build_dir}/bin/${required}")
        set(needs_deploy TRUE)
    endif()
endforeach()

if(needs_deploy)
    # A partial copy can satisfy the file checks even if deployment later fails.
    file(WRITE "${pending}" "${qt_prefix}\n")
    set(deployer "${qt_prefix}/bin/windeployqt.exe")
    if(NOT EXISTS "${deployer}")
        message(FATAL_ERROR "Qt deployment tool not found: ${deployer}")
    endif()
    message(STATUS "Deploying Qt runtime from ${qt_prefix}")
    # Let windeployqt infer the actual linkage, including release-only Qt SDKs.
    execute_process(COMMAND "${deployer}" --force
        --qmldir "${CMAKE_CURRENT_LIST_DIR}/../src/qml" --qmlimport "${build_dir}" "${executable}"
        RESULT_VARIABLE result)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "Qt deployment failed (${result}); pending deployment will be retried")
    endif()
    file(REMOVE "${pending}")
endif()
